<?php

return [
    'export_import_statistic'   => require(TMVC_MYAPPDIR . 'configs/img/export_import_statistic.php'),
    'downloadable_materials'    => require(TMVC_MYAPPDIR . 'configs/img/downloadable_materials.php'),
    'international_shippers'    => require(TMVC_MYAPPDIR . 'configs/img/international_shippers.php'),
    'category_articles_i18n'    => require(TMVC_MYAPPDIR . 'configs/img/category_articles_i18n.php'),
    'country_articles_i18n'     => require(TMVC_MYAPPDIR . 'configs/img/country_articles_i18n.php'),
    'ep_events_speakers'        => require(TMVC_MYAPPDIR . 'configs/img/ep_events_speakers.php'),
    'ep_events_partners'        => require(TMVC_MYAPPDIR . 'configs/img/ep_events_partners.php'),
    'category_articles'         => require(TMVC_MYAPPDIR . 'configs/img/category_articles.php'),
    'items_compilation'         => require(TMVC_MYAPPDIR . 'configs/img/items_compilation.php'),
    'country_articles'          => require(TMVC_MYAPPDIR . 'configs/img/country_articles.php'),
    'shipping_methods'          => require(TMVC_MYAPPDIR . 'configs/img/shipping_methods.php'),
    'company_branches'          => require(TMVC_MYAPPDIR . 'configs/img/company_branches.php'),
    'product_reviews'           => require(TMVC_MYAPPDIR . 'configs/img/product_reviews.php'),
    'dashboard_banner'          => require(TMVC_MYAPPDIR . 'configs/img/dashboard_banner.php'),
    'seller_updates'            => require(TMVC_MYAPPDIR . 'configs/img/seller_updates.php'),
    'press_releases'            => require(TMVC_MYAPPDIR . 'configs/img/press_releases.php'),
    'promo_banners'             => require(TMVC_MYAPPDIR . 'configs/img/promo_banners.php'),
    'items_draft'               => require(TMVC_MYAPPDIR . 'configs/img/items_draft.php'),
    'seller_news'               => require(TMVC_MYAPPDIR . 'configs/img/seller_news.php'),
    'trade_news'                => require(TMVC_MYAPPDIR . 'configs/img/trade_news.php'),
    'user_guide'                => require(TMVC_MYAPPDIR . 'configs/img/user_guide.php'),
    'mass_media'                => require(TMVC_MYAPPDIR . 'configs/img/mass_media.php'),
    'companies'                 => require(TMVC_MYAPPDIR . 'configs/img/companies.php'),
    'ep_events'                 => require(TMVC_MYAPPDIR . 'configs/img/ep_events.php'),
    'shippers'                  => require(TMVC_MYAPPDIR . 'configs/img/shippers.php'),
    'bloggers'                  => require(TMVC_MYAPPDIR . 'configs/img/bloggers.php'),
    'disputes'                  => require(TMVC_MYAPPDIR . 'configs/img/disputes.php'),
    'our_team'                  => require(TMVC_MYAPPDIR . 'configs/img/our_team.php'),
    'ep_news'                   => require(TMVC_MYAPPDIR . 'configs/img/ep_news.php'),
    'hiring'                    => require(TMVC_MYAPPDIR . 'configs/img/hiring.php'),
    'blogs'                     => require(TMVC_MYAPPDIR . 'configs/img/blogs.php'),
    'items'                     => require(TMVC_MYAPPDIR . 'configs/img/items.php'),
    'users'                     => require(TMVC_MYAPPDIR . 'configs/img/users.php'),
    'faq'                       => require(TMVC_MYAPPDIR . 'configs/img/faq.php'),
    'b2b_request'               => require(TMVC_MYAPPDIR . 'configs/img/b2b_request.php'),
];

