module.exports = [
    {
        label: "Community Help Question Detail",
        subdomain: "community",
        url: "/question/backstop-test-do-not-change-this-question-90",
        jsFileName: "communityQuestionDetail",
    },
    {
        label: "Community Help Question Add Reply popup",
        subdomain: "community",
        url: "/question/backstop-test-do-not-change-this-question-90",
        jsFileName: "communityQuestionDetail",
        authentication: "certified seller",
        showReplyPopup: true,
    },
    {
        label: "Community Help Question Add Reply popup error validation",
        subdomain: "community",
        url: "/question/backstop-test-do-not-change-this-question-90",
        jsFileName: "communityQuestionDetail",
        authentication: "certified seller",
        showReplyPopup: true,
        validationError: true,
    },
    {
        label: "Community Help Question success reply",
        subdomain: "community",
        url: "/question/backstop-test-do-not-change-this-question-90",
        jsFileName: "communityQuestionDetail",
        authentication: "certified seller",
        showReplyPopup: true,
        addReply: true,
    },
    {
        label: "Community Help Question Add Comment popup",
        subdomain: "community",
        url: "/question/backstop-test-do-not-change-this-question-90",
        jsFileName: "communityQuestionDetail",
        authentication: "certified seller",
        showCommentPopup: true,
    },
    {
        label: "Community Help Question Reply popup error validation",
        subdomain: "community",
        url: "/question/backstop-test-do-not-change-this-question-90",
        jsFileName: "communityQuestionDetail",
        authentication: "certified seller",
        showCommentPopup: true,
        validationError: true,
    },
    {
        label: "Community Help Question success comment",
        subdomain: "community",
        url: "/question/backstop-test-do-not-change-this-question-90",
        jsFileName: "communityQuestionDetail",
        authentication: "certified seller",
        showCommentPopup: true,
        addComment: true,
    },
    {
        label: "Community Help Question show more comments",
        subdomain: "community",
        url: "/question/backstop-test-do-not-change-this-question-90",
        jsFileName: "communityQuestionDetail",
        showMoreComments: true,
    },
]
