module.exports = [
    {
        label: "Followers Page Followers",
        url: "/backstop_test/followers",
        jsFileName: "followersPage",
        authentication: "certified seller",
    },
    {
        label: "Followers Page Show Dropdown",
        url: "/backstop_test/followers",
        jsFileName: "followersPage",
        authentication: "certified seller",
        dropdown: true,
    },
    {
        label: "Followers Page Dropdown Fill Follow",
        url: "/backstop_test/followers",
        jsFileName: "followersPage",
        authentication: "certified seller",
        dropdown: true,
        fillFollowForm: true,
    },
    {
        label: "Followers Page Dropdown Send Follow",
        url: "/backstop_test/followers",
        jsFileName: "followersPage",
        authentication: "certified seller",
        dropdown: true,
        fillFollowForm: true,
        followUser: true,
    },
    {
        label: "Followers Page Dropdown Email",
        url: "/backstop_test/followers",
        jsFileName: "followersPage",
        authentication: "certified seller",
        dropdown: true,
        email: true,
    },
    {
        label: "Followers Page Dropdown Send Email",
        url: "/backstop_test/followers",
        jsFileName: "followersPage",
        authentication: "certified seller",
        dropdown: true,
        email: true,
        sendEmail: true,
    },
    {
        label: "Followers Page Dropdown Share",
        url: "/backstop_test/followers",
        jsFileName: "followersPage",
        authentication: "certified seller",
        dropdown: true,
        share: true,
    },
    {
        label: "Followers Page Dropdown Send Share",
        url: "/backstop_test/followers",
        jsFileName: "followersPage",
        authentication: "certified seller",
        dropdown: true,
        share: true,
        sendShare: true,
    },
];
