module.exports = [
    {
        label: "Followers My Followers",
        url: "/followers/my",
        jsFileName: "followersMy",
        authentication: "certified seller",
    },
    {
        label: "Followers My Following",
        url: "/followers/my",
        jsFileName: "followersMy",
        authentication: "certified seller",
        following: true,
    },
    {
        label: "Followers My Show Dropdown",
        url: "/followers/my",
        jsFileName: "followersMy",
        authentication: "certified seller",
        dropdown: true,
    },
    {
        label: "Followers My Dropdown Fill Follow",
        url: "/followers/my",
        jsFileName: "followersMy",
        authentication: "certified seller",
        dropdown: true,
        fillFollowForm: true,
    },
    {
        label: "Followers My Dropdown Send Follow",
        url: "/followers/my",
        jsFileName: "followersMy",
        authentication: "certified seller",
        dropdown: true,
        fillFollowForm: true,
        followUser: true,
    },
    {
        label: "Followers My Dropdown Email",
        url: "/followers/my",
        jsFileName: "followersMy",
        authentication: "certified seller",
        dropdown: true,
        email: true,
    },
    {
        label: "Followers My Dropdown Send Email",
        url: "/followers/my",
        jsFileName: "followersMy",
        authentication: "certified seller",
        dropdown: true,
        email: true,
        sendEmail: true,
    },
    {
        label: "Followers My Dropdown Share",
        url: "/followers/my",
        jsFileName: "followersMy",
        authentication: "certified seller",
        dropdown: true,
        share: true,
    },
    {
        label: "Followers My Dropdown Send Share",
        url: "/followers/my",
        jsFileName: "followersMy",
        authentication: "certified seller",
        dropdown: true,
        share: true,
        sendShare: true,
    },
];
