module.exports = [
    {
        label: "Homepage seller",
        url: "/",
        jsFileName: "home",
        authentication: "certified seller",
        isSeller: true,
    },
    {
        label: "Homepage",
        url: "/",
        jsFileName: "home",
        isGuest: true,
    },
    {
        label: "Homepage dashboard switch account mobile",
        url: "/",
        jsFileName: "home",
        authentication: "certified seller",
        isSeller: true,
        showSwitchAccount: true,
    },
    {
        label: "Homepage open share",
        url: "/",
        jsFileName: "home",
        openShare: true,
        isGuest: true,
    },
    {
        label: "Homepage dashboard quick menu",
        url: "/",
        jsFileName: "home",
        authentication: "certified seller",
        isSeller: true,
        showQuickMenu: true,
    },
    {
        label: "Homepage popup categories",
        url: "/",
        jsFileName: "home",
        showPopupCategories: true,
        isGuest: true,
    },
    {
        label: "Homepage dashboard full menu",
        url: "/",
        jsFileName: "home",
        authentication: "certified seller",
        isSeller: true,
        showFullMenu: true,
    },
    {
        label: "Homepage open click to call",
        url: "/",
        jsFileName: "home",
        openClickToCall: true
    },
    {
        label: "Homepage popup user preferences",
        url: "/",
        jsFileName: "home",
        showPopupUserPreferences: true,
    },
    {
        label: "Homepage open click to call validation",
        url: "/",
        jsFileName: "home",
        openClickToCall: true,
        validate: true,
    },
    {
        label: "Homepage manufacturer",
        url: "/",
        jsFileName: "home",
        authentication: "certified manufacturer",
        isSeller: true,
    },
    {
        label: "Homepage open click to call send",
        url: "/",
        jsFileName: "home",
        openClickToCall: true,
        send: true,
    },
    {
        label: "Homepage buyer",
        url: "/",
        jsFileName: "home",
        authentication: "buyer",
        isBuyer: true,
    },
    {
        label: "Homepage freight forwarder",
        url: "/",
        jsFileName: "home",
        authentication: "freight forwarder",
        isFreightForwarder: true,
    },
    {
        label: "Homepage video popup complete profile",
        url: "/",
        jsFileName: "home",
        authentication: "certified seller",
        isSeller: true,
        showCompleteProfileVideo: true,
    },
    {
        label: "Homepage video popup add item",
        url: "/",
        jsFileName: "home",
        authentication: "certified seller",
        isSeller: true,
        showAddItemVideo: true,
    },
    {
        label: "Homepage video start selling",
        url: "/",
        jsFileName: "home",
        authentication: "certified seller",
        isSeller: true,
        showStartSellingVideo: true,
    },
];
