module.exports = [
    {
        label: "Item Question My",
        url: "/items_questions/my",
        jsFileName: "itemsQuestionsMy",
        authentication: "certified seller",
    },
    {
        label: "Item Question My Filter Popup",
        url: "/items_questions/my",
        jsFileName: "itemsQuestionsMy",
        authentication: "certified seller",
        filterPopup: true,
    },
    {
        label: "Item Question My Fill Filter Form",
        url: "/items_questions/my",
        jsFileName: "itemsQuestionsMy",
        authentication: "certified seller",
        filterPopup: true,
        fillFilterPopup: true,
    },
    {
        label: "Item Question My Active Filter Form",
        url: "/items_questions/my",
        jsFileName: "itemsQuestionsMy",
        authentication: "certified seller",
        filterPopup: true,
        fillFilterPopup: true,
        activeFilter: true,
    },
    {
        label: "Item Question My Question Details",
        url: "/items_questions/my",
        jsFileName: "itemsQuestionsMy",
        authentication: "certified seller",
        details: true,
        backstopVariant: 1,
    },
    {
        label: "Item Question My Question Details with reply",
        url: "/items_questions/my",
        jsFileName: "itemsQuestionsMy",
        authentication: "certified seller",
        details: true,
        backstopVariant: 2,
    },
    {
        label: "Item Question My Question Report This",
        url: "/items_questions/my",
        jsFileName: "itemsQuestionsMy",
        authentication: "certified seller",
        details: true,
        report: true,
    },
    {
        label: "Item Question My Question Edit Reply",
        url: "/items_questions/my",
        jsFileName: "itemsQuestionsMy",
        authentication: "certified seller",
        reply: true,
    },
    {
        label: "Item Question My Question Send Reply",
        url: "/items_questions/my",
        jsFileName: "itemsQuestionsMy",
        authentication: "certified seller",
        reply: true,
        sendReply: true,
    },
    {
        label: "Item Question My Edit Question",
        url: "/items_questions/my",
        jsFileName: "itemsQuestionsMy",
        authentication: "buyer",
        edit: true,
    },
    {
        label: "Item Question My Send Edit Question",
        url: "/items_questions/my",
        jsFileName: "itemsQuestionsMy",
        authentication: "buyer",
        edit: true,
        sendEdit: true,
    },
    {
        label: "Item Question My Delete Question",
        url: "/items_questions/my",
        jsFileName: "itemsQuestionsMy",
        authentication: "buyer",
        delete: true,
    },
]
