module.exports = [
    // ABOUT PAGE
    {
        label: "About with opened Schedule a demo popup",
        url: "/about",
        jsFileName: "about",
        type: "about",
        openScheduleDemoPopup: true,
    },
    {
        label: "About Schedule a demo popup validation error",
        url: "/about",
        jsFileName: "about",
        type: "about",
        openScheduleDemoPopup: true,
        validate: true,
    },
    {
        label: "About Schedule a demo popup submited",
        url: "/about",
        jsFileName: "about",
        type: "about",
        openScheduleDemoPopup: true,
        isSubmited: true,
    },
    // ABOUT FEATURES
    {
        label: "About features with opened Schedule a demo popup",
        url: "/about/features",
        jsFileName: "aboutFeatured",
        type: "features",
        openScheduleDemoPopup: true,
    },
    {
        label: "About features Schedule a demo popup validation error",
        url: "/about/features",
        jsFileName: "aboutFeatured",
        type: "features",
        openScheduleDemoPopup: true,
        validate: true,
    },
    {
        label: "About features Schedule a demo popup submited",
        url: "/about/features",
        jsFileName: "aboutFeatured",
        type: "features",
        openScheduleDemoPopup: true,
        isSubmited: true,
    },
    // CONTACT US
    {
        label: "Contact us with opened Schedule a demo popup",
        url: "/contact",
        jsFileName: "contactUs",
        type: "contact",
        openScheduleDemoPopup: true,
    },
    {
        label: "Contact us Schedule a demo popup validation error",
        url: "/contact",
        jsFileName: "contactUs",
        type: "contact",
        openScheduleDemoPopup: true,
        validate: true,
    },
    {
        label: "Contact us Schedule a demo popup submited",
        url: "/contact",
        jsFileName: "contactUs",
        type: "contact",
        openScheduleDemoPopup: true,
        isSubmited: true,
    },
    // FAQ
    {
        label: "FAQ with opened Schedule a demo popup",
        url: "/faq/all",
        jsFileName: "faq",
        type: "faq",
        openScheduleDemoPopup: true,
    },
    {
        label: "FAQ Schedule a demo popup validation error",
        url: "/faq/all",
        jsFileName: "faq",
        type: "faq",
        openScheduleDemoPopup: true,
        validate: true,
    },
    {
        label: "FAQ Schedule a demo popup submited",
        url: "/faq/all",
        jsFileName: "faq",
        type: "faq",
        openScheduleDemoPopup: true,
        isSubmited: true,
    },
    // HELP
    {
        label: "Help with opened Schedule a demo popup",
        url: "/help",
        jsFileName: "help",
        type: "help",
        openScheduleDemoPopup: true,
    },
    {
        label: "Help Schedule a demo popup validation error",
        url: "/help",
        jsFileName: "help",
        type: "help",
        openScheduleDemoPopup: true,
        validate: true,
    },
    {
        label: "Help Schedule a demo popup submited",
        url: "/help",
        jsFileName: "help",
        type: "help",
        openScheduleDemoPopup: true,
        isSubmited: true,
    },
    // WHY EXPORT PORTAL
    {
        label: "Why Export Portal with opened Schedule a demo popup",
        url: "/about/why_exportportal",
        jsFileName: "whyExportPortalEffectiveGlobal",
        type: "why_ep",
        openScheduleDemoPopup: true,
    },
    {
        label: "Why Export Portal Schedule a demo popup validation error",
        url: "/about/why_exportportal",
        jsFileName: "whyExportPortalEffectiveGlobal",
        type: "why_ep",
        openScheduleDemoPopup: true,
        validate: true,
    },
    {
        label: "Why Export Portal Schedule a demo popup submited",
        url: "/about/why_exportportal",
        jsFileName: "whyExportPortalEffectiveGlobal",
        type: "why_ep",
        openScheduleDemoPopup: true,
        isSubmited: true,
    },
];
