module.exports = [
    {
        label: "Seller library page",
        url: "/backstop_test/library",
        jsFileName: "sellerLibrary",
    },
    {
        label: "Seller library page logged",
        url: "/backstop_test/library",
        jsFileName: "sellerLibrary",
        authentication: "certified seller",
    },
    {
        label: "Seller library page logged header dropdown menu",
        url: "/backstop_test/library",
        jsFileName: "sellerLibrary",
        authentication: "certified seller",
        showHeaderDropdown: true,
    },
    {
        label: "Seller library page logged open add document popup",
        url: "/backstop_test/library",
        jsFileName: "sellerLibrary",
        authentication: "certified seller",
        showHeaderDropdown: true,
        openAddDocumentPopup: true,
    },
    {
        label: "Seller library page logged add document popup validation error",
        url: "/backstop_test/library",
        jsFileName: "sellerLibrary",
        authentication: "certified seller",
        showHeaderDropdown: true,
        openAddDocumentPopup: true,
        submitForm: true,
    },
    {
        label: "Seller library page logged item dropdown menu",
        url: "/backstop_test/library",
        jsFileName: "sellerLibrary",
        authentication: "certified seller",
        showDropdown: true,
    },
    {
        label: "Seller library page logged open edit document popup",
        url: "/backstop_test/library",
        jsFileName: "sellerLibrary",
        authentication: "certified seller",
        showDropdown: true,
        openEditDocumentPopup: true,
    },
    {
        label: "Seller library page logged submit edit document popup",
        url: "/backstop_test/library",
        jsFileName: "sellerLibrary",
        authentication: "certified seller",
        showDropdown: true,
        openEditDocumentPopup: true,
        submitForm: true,
    },
    {
        label: "Seller library page logged open share document popup",
        url: "/backstop_test/library",
        jsFileName: "sellerLibrary",
        authentication: "certified seller",
        showDropdown: true,
        openShareDocumentPopup: true,
    },
    {
        label: "Seller library page logged share document popup validation error",
        url: "/backstop_test/library",
        jsFileName: "sellerLibrary",
        authentication: "certified seller",
        showDropdown: true,
        openShareDocumentPopup: true,
        submitForm: true,
    },
    {
        label: "Seller library page logged submit share document popup",
        url: "/backstop_test/library",
        jsFileName: "sellerLibrary",
        authentication: "certified seller",
        showDropdown: true,
        openShareDocumentPopup: true,
        fillForm: true,
        submitForm: true,
    },
    {
        label: "Seller library page logged open email document popup",
        url: "/backstop_test/library",
        jsFileName: "sellerLibrary",
        authentication: "certified seller",
        showDropdown: true,
        openEmailDocumentPopup: true,
    },
    {
        label: "Seller library page logged email document popup validation error",
        url: "/backstop_test/library",
        jsFileName: "sellerLibrary",
        authentication: "certified seller",
        showDropdown: true,
        openEmailDocumentPopup: true,
        submitForm: true,
    },
    {
        label: "Seller library page logged submit email document popup",
        url: "/backstop_test/library",
        jsFileName: "sellerLibrary",
        authentication: "certified seller",
        showDropdown: true,
        openEmailDocumentPopup: true,
        fillForm: true,
        submitForm: true,
    },
]
