module.exports = [
    {
        label: "Seller videos page",
        url: "/backstop_test/videos",
        jsFileName: "sellerVideos",
    },
    {
        label: "Seller videos page heading dropdown menu",
        url: "/backstop_test/videos",
        jsFileName: "sellerVideos",
        authentication: "certified seller",
        showHeadingDropdown: true,
    },
    {
        label: "Seller videos page Add video popup",
        url: "/backstop_test/videos",
        jsFileName: "sellerVideos",
        authentication: "certified seller",
        showHeadingDropdown: true,
        openAddVideoPopup: true,
    },
    {
        label: "Seller videos page Add video popup validation error",
        url: "/backstop_test/videos",
        jsFileName: "sellerVideos",
        authentication: "certified seller",
        showHeadingDropdown: true,
        openAddVideoPopup: true,
        submitEmptyForm: true,
    },
    {
        label: "Seller videos page Add video success",
        url: "/backstop_test/videos",
        jsFileName: "sellerVideos",
        authentication: "certified seller",
        showHeadingDropdown: true,
        openAddVideoPopup: true,
        submitSuccessForm: true,
    },
    {
        label: "Seller videos page video dropdown menu",
        url: "/backstop_test/videos",
        jsFileName: "sellerVideos",
        authentication: "certified seller",
        showVideoDropdown: true,
    },
    {
        label: "Seller videos page share popup",
        url: "/backstop_test/videos",
        jsFileName: "sellerVideos",
        authentication: "certified seller",
        showVideoDropdown: true,
        openSharePopup: true,
    },
    {
        label: "Seller videos page share popup validation error",
        url: "/backstop_test/videos",
        jsFileName: "sellerVideos",
        authentication: "certified seller",
        showVideoDropdown: true,
        openSharePopup: true,
        submitEmptyForm: true,
    },
    {
        label: "Seller videos page send share success",
        url: "/backstop_test/videos",
        jsFileName: "sellerVideos",
        authentication: "certified manufacturer",
        showVideoDropdown: true,
        openSharePopup: true,
        submitFormSuccess: true,
    },
    {
        label: "Seller videos page email popup",
        url: "/backstop_test/videos",
        jsFileName: "sellerVideos",
        authentication: "certified manufacturer",
        showVideoDropdown: true,
        openEmailPopup: true,
    },
    {
        label: "Seller videos page email popup validation error",
        url: "/backstop_test/videos",
        jsFileName: "sellerVideos",
        authentication: "certified manufacturer",
        showVideoDropdown: true,
        openEmailPopup: true,
        submitEmptyForm: true,
    },
    {
        label: "Seller videos page send email success",
        url: "/backstop_test/videos",
        jsFileName: "sellerVideos",
        authentication: "certified manufacturer",
        showVideoDropdown: true,
        openEmailPopup: true,
        submitFormSuccess: true,
    },
    {
        label: "Seller videos page edit popup",
        url: "/backstop_test/videos",
        jsFileName: "sellerVideos",
        authentication: "certified seller",
        showVideoDropdown: true,
        openEditPopup: true,
        videoTitle: "backstop-video-test",
    },
    {
        label: "Seller videos page edit success",
        url: "/backstop_test/videos",
        jsFileName: "sellerVideos",
        authentication: "certified seller",
        showVideoDropdown: true,
        openEditPopup: true,
        submitFormSuccess: true,
    },
    {
        label: "Seller videos page report popup",
        url: "/backstop_test/videos",
        jsFileName: "sellerVideos",
        authentication: "certified manufacturer",
        showVideoDropdown: true,
        openReportPopup: true,
    },
    {
        label: "Seller videos page report popup validation error",
        url: "/backstop_test/videos",
        jsFileName: "sellerVideos",
        authentication: "certified manufacturer",
        showVideoDropdown: true,
        openReportPopup: true,
        submitEmptyForm: true,
    },
    {
        label: "Seller videos page report success",
        url: "/backstop_test/videos",
        jsFileName: "sellerVideos",
        authentication: "certified manufacturer",
        showVideoDropdown: true,
        openReportPopup: true,
        submitFormSuccess: true,
    },
];
