module.exports = [
    {
        label: "Seller updates page",
        url: "/backstop_test/updates",
        jsFileName: "sellerUpdates",
    },
    {
        label: "Seller updates page dropdown",
        url: "/backstop_test/updates",
        jsFileName: "sellerUpdates",
        dropdown: true,
    },
    {
        label: "Seller updates page dropdown share",
        url: "/backstop_test/updates",
        jsFileName: "sellerUpdates",
        authentication: "certified manufacturer",
        dropdown: true,
        share: true,
    },
    {
        label: "Seller updates page send share",
        url: "/backstop_test/updates",
        jsFileName: "sellerUpdates",
        authentication: "certified manufacturer",
        dropdown: true,
        share: true,
        sendShare: true,
    },
    {
        label: "Seller updates page dropdown email",
        url: "/backstop_test/updates",
        jsFileName: "sellerUpdates",
        authentication: "certified manufacturer",
        dropdown: true,
        email: true,
    },
    {
        label: "Seller updates page send email",
        url: "/backstop_test/updates",
        jsFileName: "sellerUpdates",
        authentication: "certified manufacturer",
        dropdown: true,
        email: true,
        sendEmail: true,
    },
    {
        label: "Seller updates page dropdown report",
        url: "/backstop_test/updates",
        jsFileName: "sellerUpdates",
        authentication: "certified manufacturer",
        dropdown: true,
        report: true,
    },
    {
        label: "Seller updates page send report",
        url: "/backstop_test/updates",
        jsFileName: "sellerUpdates",
        authentication: "certified manufacturer",
        dropdown: true,
        report: true,
        sendReport: true,
    },
    {
        label: "Seller updates page dropdown edit",
        url: "/backstop_test/updates",
        jsFileName: "sellerUpdates",
        authentication: "certified seller",
        dropdown: true,
        edit: true,
    },
];
