module.exports = [
    {
        label: "Seller news details page",
        url: "/backstop_test/view_news/lorem-ipsum-dolor-sit-amet-consectetuer-adipiscin-288",
        jsFileName: "sellerNewsDetails",
        authentication: "certified manufacturer",
    },
    {
        label: "Seller news details page dropdown",
        url: "/backstop_test/view_news/lorem-ipsum-dolor-sit-amet-consectetuer-adipiscin-288",
        jsFileName: "sellerNewsDetails",
        dropdown: true,
    },
    {
        label: "Seller news details page dropdown share",
        url: "/backstop_test/view_news/lorem-ipsum-dolor-sit-amet-consectetuer-adipiscin-288",
        jsFileName: "sellerNewsDetails",
        authentication: "certified manufacturer",
        dropdown: true,
        share: true,
    },
    {
        label: "Seller news details page dropdown send share",
        url: "/backstop_test/view_news/lorem-ipsum-dolor-sit-amet-consectetuer-adipiscin-288",
        jsFileName: "sellerNewsDetails",
        authentication: "certified manufacturer",
        dropdown: true,
        share: true,
        sendShare: true,
    },
    {
        label: "Seller news details page dropdown email",
        url: "/backstop_test/view_news/lorem-ipsum-dolor-sit-amet-consectetuer-adipiscin-288",
        jsFileName: "sellerNewsDetails",
        authentication: "certified manufacturer",
        dropdown: true,
        email: true,
    },
    {
        label: "Seller news details page dropdown send email",
        url: "/backstop_test/view_news/lorem-ipsum-dolor-sit-amet-consectetuer-adipiscin-288",
        jsFileName: "sellerNewsDetails",
        authentication: "certified manufacturer",
        dropdown: true,
        email: true,
        sendEmail: true,
    },
    {
        label: "Seller news details page dropdown report",
        url: "/backstop_test/view_news/lorem-ipsum-dolor-sit-amet-consectetuer-adipiscin-288",
        jsFileName: "sellerNewsDetails",
        authentication: "certified manufacturer",
        dropdown: true,
        report: true,
    },
    {
        label: "Seller news details page dropdown send report",
        url: "/backstop_test/view_news/lorem-ipsum-dolor-sit-amet-consectetuer-adipiscin-288",
        jsFileName: "sellerNewsDetails",
        authentication: "certified manufacturer",
        dropdown: true,
        report: true,
        sendReport: true,
    },
    {
        label: "Seller news details page edit comment form",
        url: "/backstop_test/view_news/lorem-ipsum-dolor-sit-amet-consectetuer-adipiscin-288",
        jsFileName: "sellerNewsDetails",
        authentication: "certified manufacturer",
        editComment: true,
    },
    {
        label: "Seller news details page send edit comment form",
        url: "/backstop_test/view_news/lorem-ipsum-dolor-sit-amet-consectetuer-adipiscin-288",
        jsFileName: "sellerNewsDetails",
        authentication: "certified manufacturer",
        editComment: true,
        sendEditComment: true,
    },
    {
        label: "Seller news details page delete comment",
        url: "/backstop_test/view_news/lorem-ipsum-dolor-sit-amet-consectetuer-adipiscin-288",
        jsFileName: "sellerNewsDetails",
        authentication: "certified manufacturer",
        delete: true,
    },
    {
        label: "Seller news details page report comment",
        url: "/backstop_test/view_news/lorem-ipsum-dolor-sit-amet-consectetuer-adipiscin-288",
        jsFileName: "sellerNewsDetails",
        authentication: "certified seller",
        reportComment: true,
    },
    {
        label: "Seller news details page send report comment",
        url: "/backstop_test/view_news/lorem-ipsum-dolor-sit-amet-consectetuer-adipiscin-288",
        jsFileName: "sellerNewsDetails",
        authentication: "certified seller",
        reportComment: true,
        sendReportComment: true,
    },
];
