module.exports = [
    {
        label: "Seller pictures page",
        url: "/backstop_test/pictures",
        jsFileName: "sellerPictures",
    },
    {
        label: "Seller pictures page heading dropdown menu",
        url: "/backstop_test/pictures",
        jsFileName: "sellerPictures",
        authentication: "certified seller",
        showHeadingDropdown: true,
    },
    {
        label: "Seller pictures page Add picture popup",
        url: "/backstop_test/pictures",
        jsFileName: "sellerPictures",
        authentication: "certified seller",
        showHeadingDropdown: true,
        openAddPicturePopup: true,
    },
    {
        label: "Seller pictures page Add picture popup validation error",
        url: "/backstop_test/pictures",
        jsFileName: "sellerPictures",
        authentication: "certified seller",
        showHeadingDropdown: true,
        openAddPicturePopup: true,
        submitEmptyForm: true,
    },
    {
        label: "Seller pictures page picture dropdown menu",
        url: "/backstop_test/pictures",
        jsFileName: "sellerPictures",
        authentication: "certified seller",
        showPictureDropdown: true,
    },
    {
        label: "Seller pictures page share popup",
        url: "/backstop_test/pictures",
        jsFileName: "sellerPictures",
        authentication: "certified seller",
        showPictureDropdown: true,
        openSharePopup: true,
    },
    {
        label: "Seller pictures page share popup validation error",
        url: "/backstop_test/pictures",
        jsFileName: "sellerPictures",
        authentication: "certified seller",
        showPictureDropdown: true,
        openSharePopup: true,
        submitEmptyForm: true,
    },
    {
        label: "Seller pictures page send share success",
        url: "/backstop_test/pictures",
        jsFileName: "sellerPictures",
        authentication: "certified manufacturer",
        showPictureDropdown: true,
        openSharePopup: true,
        submitFormSuccess: true,
    },
    {
        label: "Seller pictures page email popup",
        url: "/backstop_test/pictures",
        jsFileName: "sellerPictures",
        authentication: "certified manufacturer",
        showPictureDropdown: true,
        openEmailPopup: true,
    },
    {
        label: "Seller pictures page email popup validation error",
        url: "/backstop_test/pictures",
        jsFileName: "sellerPictures",
        authentication: "certified manufacturer",
        showPictureDropdown: true,
        openEmailPopup: true,
        submitEmptyForm: true,
    },
    {
        label: "Seller pictures page send email success",
        url: "/backstop_test/pictures",
        jsFileName: "sellerPictures",
        authentication: "certified manufacturer",
        showPictureDropdown: true,
        openEmailPopup: true,
        submitFormSuccess: true,
    },
    {
        label: "Seller pictures page edit popup",
        url: "/backstop_test/pictures",
        jsFileName: "sellerPictures",
        authentication: "certified seller",
        showPictureDropdown: true,
        openEditPopup: true,
    },
    {
        label: "Seller pictures page edit success",
        url: "/backstop_test/pictures",
        jsFileName: "sellerPictures",
        authentication: "certified seller",
        showPictureDropdown: true,
        openEditPopup: true,
        submitFormSuccess: true,
    },
];
