module.exports = [
    {
        label: "Seller feedbacks EP page",
        url: "/backstop_test/feedbacks_ep",
        jsFileName: "sellerFeedbacks",
    },
    {
        label: "Seller feedbacks EP page logged",
        url: "/backstop_test/feedbacks_ep",
        jsFileName: "sellerFeedbacks",
        authentication: "certified seller",
    },
    {
        label: "Seller feedbacks EP page logged dropdown menu",
        url: "/backstop_test/feedbacks_ep",
        jsFileName: "sellerFeedbacks",
        authentication: "certified seller",
        showDropdown: true,
    },
    {
        label: "Seller feedbacks EP page logged open add report popup",
        url: "/backstop_test/feedbacks_ep",
        jsFileName: "sellerFeedbacks",
        authentication: "certified seller",
        showDropdown: true,
        openAddReportPopup: true,
    },
    {
        label: "Seller feedbacks EP page logged add report popup validation error",
        url: "/backstop_test/feedbacks_ep",
        jsFileName: "sellerFeedbacks",
        authentication: "certified seller",
        showDropdown: true,
        openAddReportPopup: true,
        submitForm: true,
    },
    {
        label: "Seller feedbacks EP page logged submit add report popup",
        url: "/backstop_test/feedbacks_ep",
        jsFileName: "sellerFeedbacks",
        authentication: "certified seller",
        showDropdown: true,
        openAddReportPopup: true,
        fillForm: true,
        submitForm: true,
    },
    {
        label: "Seller feedbacks EP page logged open edit reply popup",
        url: "/backstop_test/feedbacks_ep",
        jsFileName: "sellerFeedbacks",
        authentication: "certified seller",
        showDropdown: true,
        openEditReplyPopup: true,
    },
    {
        label: "Seller feedbacks EP page logged submit edit reply popup",
        url: "/backstop_test/feedbacks_ep",
        jsFileName: "sellerFeedbacks",
        authentication: "certified seller",
        showDropdown: true,
        openEditReplyPopup: true,
        submitForm: true,
    },
    {
        label: "Seller feedbacks EP page logged open add reply popup",
        url: "/backstop_test/feedbacks_ep",
        jsFileName: "sellerFeedbacks",
        authentication: "certified seller",
        showDropdown: true,
        openAddReplyPopup: true,
    },
    {
        label: "Seller feedbacks EP page logged add reply popup validation error",
        url: "/backstop_test/feedbacks_ep",
        jsFileName: "sellerFeedbacks",
        authentication: "certified seller",
        showDropdown: true,
        openAddReplyPopup: true,
        submitForm: true,
    },
    {
        label: "Seller feedbacks EP page logged fill add reply popup",
        url: "/backstop_test/feedbacks_ep",
        jsFileName: "sellerFeedbacks",
        authentication: "certified seller",
        showDropdown: true,
        openAddReplyPopup: true,
        fillForm: true,
    },
]
