module.exports = [
    {
        label: "Seller library detail page",
        url: "/backstop_test/document/253",
        jsFileName: "sellerLibraryDocument",
    },
    {
        label: "Seller library detail page logged",
        url: "/backstop_test/document/253",
        jsFileName: "sellerLibraryDocument",
        authentication: "certified seller",
    },
    {
        label: "Seller library detail page logged open email document popup",
        url: "/backstop_test/document/253",
        jsFileName: "sellerLibraryDocument",
        authentication: "certified seller",
        openEmailDocumentPopup: true,
    },
    {
        label: "Seller library detail page logged email document popup validation error",
        url: "/backstop_test/document/253",
        jsFileName: "sellerLibraryDocument",
        authentication: "certified seller",
        openEmailDocumentPopup: true,
        submitForm: true,
    },
    {
        label: "Seller library detail page logged submit email document popup",
        url: "/backstop_test/document/253",
        jsFileName: "sellerLibraryDocument",
        authentication: "certified seller",
        openEmailDocumentPopup: true,
        fillForm: true,
        submitForm: true,
    },
    {
        label: "Seller library detail page logged open share document popup",
        url: "/backstop_test/document/253",
        jsFileName: "sellerLibraryDocument",
        authentication: "certified seller",
        openShareDocumentPopup: true,
    },
    {
        label: "Seller library detail page logged share document popup validation error",
        url: "/backstop_test/document/253",
        jsFileName: "sellerLibraryDocument",
        authentication: "certified seller",
        openShareDocumentPopup: true,
        submitForm: true,
    },
    {
        label: "Seller library detail page logged submit share document popup",
        url: "/backstop_test/document/253",
        jsFileName: "sellerLibraryDocument",
        authentication: "certified seller",
        openShareDocumentPopup: true,
        fillForm: true,
        submitForm: true,
    },
    {
        label: "Seller library detail page logged item dropdown menu",
        url: "/backstop_test/document/253",
        jsFileName: "sellerLibraryDocument",
        authentication: "certified seller",
        showItemDropdown: true,
    },
    {
        label: "Seller library detail page logged open edit document popup",
        url: "/backstop_test/document/253",
        jsFileName: "sellerLibraryDocument",
        authentication: "certified seller",
        showItemDropdown: true,
        openEditDocumentPopup: true,
    },
    {
        label: "Seller library detail page logged submit edit document popup",
        url: "/backstop_test/document/253",
        jsFileName: "sellerLibraryDocument",
        authentication: "certified seller",
        showItemDropdown: true,
        openEditDocumentPopup: true,
        submitForm: true,
    },
    {
        label: "Seller library detail page logged open share document popup",
        url: "/backstop_test/document/253",
        jsFileName: "sellerLibraryDocument",
        authentication: "certified seller",
        showItemDropdown: true,
        openItemShareDocumentPopup: true,
    },
    {
        label: "Seller library detail page logged share document popup validation error",
        url: "/backstop_test/document/253",
        jsFileName: "sellerLibraryDocument",
        authentication: "certified seller",
        showItemDropdown: true,
        openItemShareDocumentPopup: true,
        submitForm: true,
    },
    {
        label: "Seller library detail page logged submit share document popup",
        url: "/backstop_test/document/253",
        jsFileName: "sellerLibraryDocument",
        authentication: "certified seller",
        showItemDropdown: true,
        openItemShareDocumentPopup: true,
        fillForm: true,
        submitForm: true,
    },
    {
        label: "Seller library detail page logged open email document popup",
        url: "/backstop_test/document/253",
        jsFileName: "sellerLibraryDocument",
        authentication: "certified seller",
        showItemDropdown: true,
        openItemEmailDocumentPopup: true,
    },
    {
        label: "Seller library detail page logged email document popup validation error",
        url: "/backstop_test/document/253",
        jsFileName: "sellerLibraryDocument",
        authentication: "certified seller",
        showItemDropdown: true,
        openItemEmailDocumentPopup: true,
        submitForm: true,
    },
    {
        label: "Seller library detail page logged submit email document popup",
        url: "/backstop_test/document/253",
        jsFileName: "sellerLibraryDocument",
        authentication: "certified seller",
        showItemDropdown: true,
        openItemEmailDocumentPopup: true,
        fillForm: true,
        submitForm: true,
    },
]
