module.exports = [
    {
        label: "Seller news page",
        url: "/backstop_test/news",
        jsFileName: "sellerNews",
    },
    {
        label: "Seller news page dropdown",
        url: "/backstop_test/news",
        jsFileName: "sellerNews",
        dropdown: true,
    },
    {
        label: "Seller news page Add news",
        url: "/backstop_test/news",
        jsFileName: "sellerNews",
        authentication: "certified seller",
        addNews: true,
    },
    {
        label: "Seller news page dropdown share",
        url: "/backstop_test/news",
        jsFileName: "sellerNews",
        authentication: "buyer",
        dropdown: true,
        share: true,
    },
    {
        label: "Seller news page send share",
        url: "/backstop_test/news",
        jsFileName: "sellerNews",
        authentication: "certified manufacturer",
        dropdown: true,
        share: true,
        sendShare: true,
    },
    {
        label: "Seller news page dropdown email",
        url: "/backstop_test/news",
        jsFileName: "sellerNews",
        authentication: "buyer",
        dropdown: true,
        email: true,
    },
    {
        label: "Seller news page send email",
        url: "/backstop_test/news",
        jsFileName: "sellerNews",
        authentication: "buyer",
        dropdown: true,
        email: true,
        sendEmail: true,
    },
    {
        label: "Seller news page dropdown report",
        url: "/backstop_test/news",
        jsFileName: "sellerNews",
        authentication: "buyer",
        dropdown: true,
        report: true,
    },
    {
        label: "Seller news page send report",
        url: "/backstop_test/news",
        jsFileName: "sellerNews",
        authentication: "buyer",
        dropdown: true,
        report: true,
        sendReport: true,
    },
    {
        label: "Seller news page dropdown edit",
        url: "/backstop_test/news",
        jsFileName: "sellerNews",
        authentication: "certified seller",
        dropdown: true,
        edit: true,
    },
];
